#! /bin/bash

STATUS="$(amixer sget Master | tail -n1 | sed -r "s/.*\[(.*)\]/\1/")"
VOL="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"

if [ "$STATUS" = "off" ]
then
  echo -e "MUTE"
else
  echo -e "VOL: $VOL%"
fi

